repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v4.2.0
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.14.3
  hooks:
    - id: check-github-workflows
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
    - id: black
- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
    - id: flake8
      additional_dependencies: ['flake8-bugbear==22.1.11']
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
    - id: isort
- repo: https://github.com/asottile/pyupgrade
  rev: v2.32.0
  hooks:
    - id: pyupgrade
      args: ["--py36-plus"]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.950
  hooks:
    - id: mypy
      files: ^src/funcx_common/
      additional_dependencies: ['types-redis', 'pydantic']
