repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v4.4.0
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.23.1
  hooks:
    - id: check-dependabot
    - id: check-github-workflows
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
    - id: black
- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
      additional_dependencies: ['flake8-bugbear==22.12.6']
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
    - id: isort
- repo: https://github.com/asottile/pyupgrade
  rev: v3.4.0
  hooks:
    - id: pyupgrade
      args: ["--py36-plus"]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.3.0
  hooks:
    - id: mypy
      files: ^src/globus_compute_common/
      additional_dependencies: ['types-redis', 'pydantic']
