repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v4.5.0
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.27.1
  hooks:
    - id: check-dependabot
    - id: check-github-workflows
- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.0
  hooks:
    - id: pyupgrade
      args: ["--py37-plus"]
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.11.0
  hooks:
    - id: black
- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
    - id: flake8
      additional_dependencies: ['flake8-bugbear==22.12.6']
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
    - id: isort
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.7.0
  hooks:
    - id: mypy
      files: ^src/globus_compute_common/
      additional_dependencies: ['types-redis', 'pydantic>=1,<2']
