name: build
on:
  push:
  pull_request:
  # build weekly at 4:00 AM UTC
  schedule:
    - cron: '0 4 * * 1'
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9"]
        include:
          - os: ubuntu-latest
            python-version: 3.6
          - os: ubuntu-latest
            python-version: 3.7
          - os: ubuntu-latest
            python-version: 3.8
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }} "
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: start redis
        if: runner.os == 'Linux'
        uses: ./.github/actions/redis
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install requirements
        run: |
          python -m pip install -U tox
      - name: lint
        # only lint on 3.9 for faster overall runs
        if: matrix.python-version == '3.9'
        run: python -m tox -e lint,mypy
      - name: test
        run: python -m tox -e py,py-noredis -- --cov-report="term-missing:skip-covered"
